namespace LXGaming.Hosting.Generators.Utilities {

    public static class Constants {

        public static class Types {

            public const string ServiceAttribute = "LXGaming.Hosting.ServiceAttribute";
            public const string KeyedServiceAttribute = "LXGaming.Hosting.KeyedServiceAttribute";

            public const string ServiceLifetime = "Microsoft.Extensions.DependencyInjection.ServiceLifetime";
            public const string ServiceLifetimeSingleton = ServiceLifetime + ".Singleton";
            public const string HostedService = "Microsoft.Extensions.Hosting.IHostedService";
        }

        public static class Source {

            public static readonly string Indent = new string(' ', 12);

            public const string StartRegion = "#region {0}";
            public const string EndRegion = "#endregion";

            public const string ServiceExtensions = @"// <auto-generated/>
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace LXGaming.Hosting {

    internal static class ServiceExtensions {

        public static IServiceCollection AddAllServices(this IServiceCollection services) {
{0}
            return services;
        }
    }
}";

            public const string ServiceDescriptorType = @"services.Add(new ServiceDescriptor(
    {0},
    {1},
    {2}));";

            public const string ServiceDescriptorFactory = @"services.Add(new ServiceDescriptor(
    {0},
    provider => provider.GetRequiredService({1}),
    {2}));";

            public const string KeyedServiceDescriptorType = @"services.Add(new ServiceDescriptor(
    {0},
    {1},
    {2},
    {3}));";

            public const string KeyedServiceDescriptorFactory = @"services.Add(new ServiceDescriptor(
    {0},
    {1},
    (provider, key) => provider.GetRequiredKeyedService({2}, key),
    {3}));";
        }
    }
}